stages:
  - docker-build

docker-build:
  stage: docker-build
  image: docker:latest
  script:
    # 下载阿里巴巴 JDK 8
    # https://dragonwell.oss-cn-shanghai.aliyuncs.com/8/x64/8.1.1-GA/Alibaba_Dragonwell_8.1.1-GA_Linux_x64.tar.gz
    - wget https://github.com/alibaba/dragonwell8/releases/download/v8.1.1-GA/Alibaba_Dragonwell_8.1.1-GA_Linux_x64.tar.gz
    - docker build -t dragonwell:8.1.1 .
  after_script:
    - docker images
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker tag dragonwell:8.1.1 $DOCKER_USERNAME/dragonwell:8.1.1
    - docker images
    - docker push $DOCKER_USERNAME/dragonwell:8.1.1
  # https://docs.gitlab.com/ee/ci/yaml/index.html#rules
  rules:
    - if: $CI_COMMIT_TAG
