stages:
  - docker-build

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  script:
    # 下载阿里巴巴 JDK 8
    # https://dragonwell.oss-cn-shanghai.aliyuncs.com/8/8.5.5-GA/Alibaba_Dragonwell_8.5.5-GA_Linux_x64.tar.gz
    - wget https://github.com/alibaba/dragonwell8/releases/download/dragonwell-8.5.5_jdk8u275-ga/Alibaba_Dragonwell_8.5.5-GA_Linux_x64.tar.gz
    - docker build -t dragonwell8:8.5.5 .
  after_script:
    - docker images
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker tag dragonwell8:8.5.5 $DOCKER_USERNAME/dragonwell8:8.5.5
    - docker images
    - docker push $DOCKER_USERNAME/dragonwell8:8.5.5
  # https://docs.gitlab.com/ee/ci/yaml/index.html#rules
  rules:
    - if: $CI_COMMIT_TAG
