stages:
  - docker-build

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  script:
    # 下载阿里巴巴 JDK 8
    # https://dragonwell.oss-cn-shanghai.aliyuncs.com/8.7.7/Alibaba_Dragonwell_8.7.7_x64_linux.tar.gz
    - wget https://github.com/alibaba/dragonwell8/releases/download/dragonwell-8.7.7_jdk8u292-ga/Alibaba_Dragonwell_8.7.7_x64_linux.tar.gz
    - docker build -t dragonwell8:8.7.7 .
  after_script:
    - docker images
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker tag dragonwell8:8.7.7 $DOCKER_USERNAME/dragonwell8:8.7.7
    - docker images
    - docker push $DOCKER_USERNAME/dragonwell8:8.7.7
  # https://docs.gitlab.com/ee/ci/yaml/index.html#rules
  rules:
    - if: $CI_COMMIT_TAG
