stages:
  - docker-build

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  script:
    # 下载阿里巴巴 JDK 8
    # https://dragonwell.oss-cn-shanghai.aliyuncs.com/8.9.10/Alibaba_Dragonwell_8.9.10_x64_linux.tar.gz
    - wget https://dragonwell.oss-cn-shanghai.aliyuncs.com/8.9.10/Alibaba_Dragonwell_8.9.10_x64_linux.tar.gz
    - docker build -t dragonwell8:8.9.10 .
  after_script:
    - docker images
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker tag dragonwell8:8.9.10 $DOCKER_USERNAME/dragonwell8:8.9.10
    - docker images
    - docker push $DOCKER_USERNAME/dragonwell8:8.9.10
  # https://docs.gitlab.com/ee/ci/yaml/index.html#rules
  rules:
    - if: $CI_COMMIT_TAG
